// Generated by scripts/sync-nucleo-icons.js from nucleo-map.json. Do not edit by hand.
import { createIcon } from "./createIcon";
import * as Nucleo from "./nucleo";

export type { IconComponent, IconProps } from "./createIcon";
export {
  Bold,
  Circle,
  Heading,
  Italic,
  List,
  ListChecks,
  ListOrdered,
  Quote,
  Square,
  Strikethrough,
  Table,
} from "./primitives";

export const AlertCircle = createIcon("alert-circle", Nucleo.CircleWarningOutline24);
export const AlertTriangle = createIcon("alert-triangle", Nucleo.TriangleWarningOutline24);
export const AlignLeft = createIcon("align-left", Nucleo.TextAlignLeftOutline24);
export const Archive = createIcon("archive", Nucleo.BoxArchiveOutline24);
export const ArchiveRestore = createIcon("archive-restore", Nucleo.ArchiveExportOutline24);
export const ArrowLeft = createIcon("arrow-left", Nucleo.ArrowLeftOutline24);
export const ArrowRight = createIcon("arrow-right", Nucleo.ArrowRightOutline24);
export const ArrowUpDown = createIcon("arrow-up-down", Nucleo.ArrowsOppositeDirectionYOutline24);
export const AudioLines = createIcon("audio-lines", Nucleo.WaveformLinesOutline24);
export const BanknoteCheck = createIcon("banknote-check", Nucleo.MoneyBillOutline24);
export const BarChart3 = createIcon("bar-chart-3", Nucleo.ChartOutline24);
export const Blocks = createIcon("blocks", Nucleo.GridOutline24);
export const BookOpen = createIcon("book-open", Nucleo.BookOpenOutline24);
export const Brain = createIcon("brain", Nucleo.BrainOutline24);
export const Bug = createIcon("bug", Nucleo.BugOutline24);
export const Building2 = createIcon("building-2", Nucleo.Office2Outline24);
export const Calendar = createIcon("calendar", Nucleo.CalendarOutline24);
export const CalendarCheck = createIcon("calendar-check", Nucleo.CalendarCheckOutline24);
export const CalendarDays = createIcon("calendar-days", Nucleo.CalendarEventOutline24);
export const Check = createIcon("check", Nucleo.CheckOutline24);
export const CheckCircle = createIcon("check-circle", Nucleo.CircleCheckOutline24);
export const CheckCircle2 = createIcon("check-circle-2", Nucleo.CircleCheckOutline24);
export const ChevronDown = createIcon("chevron-down", Nucleo.ChevronDownOutline24);
export const ChevronLeft = createIcon("chevron-left", Nucleo.ChevronLeftOutline24);
export const ChevronRight = createIcon("chevron-right", Nucleo.ChevronRightOutline24);
export const ChevronUp = createIcon("chevron-up", Nucleo.ChevronUpOutline24);
export const CircleAlert = createIcon("circle-alert", Nucleo.CircleWarningOutline24);
export const CircleCheck = createIcon("circle-check", Nucleo.CircleCheckOutline24);
export const CircleX = createIcon("circle-x", Nucleo.CircleXmarkOutline24);
export const ClipboardCheck = createIcon("clipboard-check", Nucleo.ClipboardCheckOutline24);
export const Clock = createIcon("clock", Nucleo.ClockOutline24);
export const Clock3 = createIcon("clock-3", Nucleo.ClockOutline24);
export const Cloud = createIcon("cloud", Nucleo.Cloud2Outline24);
export const CloudUpload = createIcon("cloud-upload", Nucleo.CloudUpload2Outline24);
export const Code2 = createIcon("code-2", Nucleo.CodeOutline24);
export const Copy = createIcon("copy", Nucleo.Copy2Outline24);
export const CornerDownLeft = createIcon("corner-down-left", Nucleo.ArrowTurnLeftOutline24);
export const Cpu = createIcon("cpu", Nucleo.MicrochipOutline24);
export const CreditCard = createIcon("credit-card", Nucleo.CreditCardOutline24);
export const Crown = createIcon("crown", Nucleo.CrownOutline24);
export const Download = createIcon("download", Nucleo.DownloadOutline24);
export const Edit3 = createIcon("edit-3", Nucleo.PenOutline24);
export const ExternalLink = createIcon("external-link", Nucleo.ExternalLinkOutline24);
export const Eye = createIcon("eye", Nucleo.EyeOutline24);
export const FileAudio = createIcon("file-audio", Nucleo.FileMusicOutline24);
export const FilePen = createIcon("file-pen", Nucleo.FilePenOutline24);
export const FilePlus = createIcon("file-plus", Nucleo.FileNewOutline24);
export const FileSearch = createIcon("file-search", Nucleo.FileSearchOutline24);
export const FileText = createIcon("file-text", Nucleo.FileContentOutline24);
export const Flame = createIcon("flame", Nucleo.FireFlameOutline24);
export const Folder = createIcon("folder", Nucleo.FolderOutline24);
export const FolderOpen = createIcon("folder-open", Nucleo.FolderOpenOutline24);
export const GalleryVerticalEnd = createIcon("gallery-vertical-end", Nucleo.Layers2Outline24);
export const Gauge = createIcon("gauge", Nucleo.Gauge4Outline24);
export const Gift = createIcon("gift", Nucleo.GiftOutline24);
export const Globe = createIcon("globe", Nucleo.GlobeOutline24);
export const Globe2 = createIcon("globe-2", Nucleo.GlobeOutline24);
export const HardDrive = createIcon("hard-drive", Nucleo.HardDriveOutline24);
export const HelpCircle = createIcon("help-circle", Nucleo.CircleQuestionOutline24);
export const Home = createIcon("home", Nucleo.House4Outline24);
export const Info = createIcon("info", Nucleo.CircleInfoOutline24);
export const Key = createIcon("key", Nucleo.KeyOutline24);
export const Keyboard = createIcon("keyboard", Nucleo.KeyboardOutline24);
export const KeyRound = createIcon("key-round", Nucleo.KeyOutline24);
export const Languages = createIcon("languages", Nucleo.LanguageOutline24);
export const Laptop = createIcon("laptop", Nucleo.LaptopOutline24);
export const Link = createIcon("link", Nucleo.LinkOutline24);
export const Link2 = createIcon("link-2", Nucleo.LinkOutline24);
export const LinkIcon = createIcon("link-icon", Nucleo.LinkOutline24);
export const Loader = createIcon("loader", Nucleo.CircularLoaderOutline24);
export const Loader2 = createIcon("loader-2", Nucleo.CircularLoaderOutline24);
export const LocateFixed = createIcon("locate-fixed", Nucleo.CrosshairsOutline24);
export const Lock = createIcon("lock", Nucleo.LockOutline24);
export const LogIn = createIcon("log-in", Nucleo.RectLoginOutline24);
export const LogOut = createIcon("log-out", Nucleo.RectLogoutOutline24);
export const Mail = createIcon("mail", Nucleo.EnvelopeOutline24);
export const MailCheck = createIcon("mail-check", Nucleo.EnvelopeOutline24);
export const Medal = createIcon("medal", Nucleo.AwardMedalOutline24);
export const MessageCircle = createIcon("message-circle", Nucleo.MsgOutline24);
export const MessageSquare = createIcon("message-square", Nucleo.MessageOutline24);
export const MessageSquareText = createIcon("message-square-text", Nucleo.Message2ContentOutline24);
export const Mic = createIcon("mic", Nucleo.MicrophoneOutline24);
export const Mic2 = createIcon("mic-2", Nucleo.Microphone5Outline24);
export const MicVocal = createIcon("mic-vocal", Nucleo.Microphone5Outline24);
export const Minus = createIcon("minus", Nucleo.MinusOutline24);
export const Monitor = createIcon("monitor", Nucleo.MonitorOutline24);
export const MonitorSmartphone = createIcon("monitor-smartphone", Nucleo.MonitorMobileOutline24);
export const Moon = createIcon("moon", Nucleo.MoonOutline24);
export const MoreHorizontal = createIcon("more-horizontal", Nucleo.DotsOutline24);
export const MoreVertical = createIcon("more-vertical", Nucleo.DotsVerticalOutline24);
export const MousePointer2 = createIcon("mouse-pointer-2", Nucleo.PointerOutline24);
export const MousePointerClick = createIcon("mouse-pointer-click", Nucleo.Cursor2Outline24);
export const Network = createIcon("network", Nucleo.NetworkNodesOutline24);
export const NotebookPen = createIcon("notebook-pen", Nucleo.NotebookOutline24);
export const PanelLeftClose = createIcon("panel-left-close", Nucleo.LayoutLeftOutline24);
export const PanelLeftOpen = createIcon("panel-left-open", Nucleo.LayoutLeftOutline24);
export const PanelRight = createIcon("panel-right", Nucleo.LayoutRightOutline24);
export const PanelRightClose = createIcon("panel-right-close", Nucleo.SidebarRightOutline24);
export const Pencil = createIcon("pencil", Nucleo.PencilOutline24);
export const Play = createIcon("play", Nucleo.MediaPlayOutline24);
export const Plus = createIcon("plus", Nucleo.PlusOutline24);
export const RefreshCw = createIcon("refresh-cw", Nucleo.RefreshOutline24);
export const RotateCcw = createIcon("rotate-ccw", Nucleo.Redo2Outline18);
export const RotateCw = createIcon("rotate-cw", Nucleo.ArrowRotateClockwiseOutline24);
export const Save = createIcon("save", Nucleo.FloppyDiskOutline24);
export const ScrollText = createIcon("scroll-text", Nucleo.FileContentOutline24);
export const Search = createIcon("search", Nucleo.MagnifierOutline24);
export const Send = createIcon("send", Nucleo.PaperPlane2Outline24);
export const Server = createIcon("server", Nucleo.ServerOutline24);
export const Settings = createIcon("settings", Nucleo.GearOutline24);
export const Settings2 = createIcon("settings-2", Nucleo.Sliders2Outline24);
export const Share2 = createIcon("share-2", Nucleo.ShareRight2Outline24);
export const Shield = createIcon("shield", Nucleo.ShieldOutline24);
export const ShieldCheck = createIcon("shield-check", Nucleo.ShieldCheckOutline24);
export const Sliders = createIcon("sliders", Nucleo.Sliders2VerticalOutline24);
export const Smile = createIcon("smile", Nucleo.FaceSmileOutline24);
export const Sparkles = createIcon("sparkles", Nucleo.SparkleOutline24);
export const SquarePen = createIcon("square-pen", Nucleo.ComposeOutline24);
export const Sun = createIcon("sun", Nucleo.SunOutline24);
export const Terminal = createIcon("terminal", Nucleo.ConsoleOutline24);
export const TestTube = createIcon("test-tube", Nucleo.TestTubeOutline24);
export const Trash2 = createIcon("trash-2", Nucleo.TrashOutline24);
export const Trophy = createIcon("trophy", Nucleo.TrophyOutline24);
export const Undo2 = createIcon("undo-2", Nucleo.UndoOutline24);
export const Unlink = createIcon("unlink", Nucleo.LinkBrokenOutline24);
export const Upload = createIcon("upload", Nucleo.Upload4Outline24);
export const User = createIcon("user", Nucleo.UserOutline24);
export const UserCircle = createIcon("user-circle", Nucleo.CircleUserOutline24);
export const UserPlus = createIcon("user-plus", Nucleo.UserPlusOutline24);
export const UserRound = createIcon("user-round", Nucleo.UserOutline24);
export const Users = createIcon("users", Nucleo.UsersOutline24);
export const UsersRound = createIcon("users-round", Nucleo.UsersOutline24);
export const Video = createIcon("video", Nucleo.Video2Outline24);
export const Wand2 = createIcon("wand-2", Nucleo.WandSparkleOutline24);
export const WandSparkles = createIcon("wand-sparkles", Nucleo.WandSparkleOutline24);
export const WifiOff = createIcon("wifi-off", Nucleo.WifiOffOutline24);
export const Wrench = createIcon("wrench", Nucleo.WrenchOutline24);
export const X = createIcon("x", Nucleo.XmarkOutline24);
export const XCircle = createIcon("xcircle", Nucleo.CircleXmarkOutline24);
export const Zap = createIcon("zap", Nucleo.BoltOutline24);
